// Compiles a littlefoot program with the BLOCKS SDK compiler and writes it as a JS file for the web editor.
// Placeholders are int literals the compiler emits as push32 with a 4-byte operand: 0x5A5A0000 + n for the
// values the editor patches (n = 0, 1, 2... without gaps, each used once), and 0x5A5A00FF, replaced here by a
// build id hashed from the program so the editor can tell whether a keyboard runs the same build.
// usage: lfgen program.littlefoot out.js out.bin VARIABLE_NAME
#include <juce_core/juce_core.h>
#include <cstdio>
#include <vector>
namespace roli { using namespace juce; }
namespace littlefoot { using juce::readLittleEndianBitsInBuffer; }
#include "roli_LittleFootRunner.h"
#include "roli_LittleFootCompiler.h"
#include "natives.inc"

using namespace littlefoot;

static const uint32 placeholderBase = 0x5A5A0000u;
static const uint32 buildIdPlaceholder = placeholderBase + 0xFFu;

// Operand offsets of every push32 of value v
static std::vector<int> findOperands (const std::vector<uint8>& code, uint32 v)
{
    std::vector<int> found;

    for (size_t i = 0; i + 4 < code.size(); ++i)
        if (code[i] == (uint8) OpCode::push32
             && code[i + 1] == (uint8) v && code[i + 2] == (uint8) (v >> 8)
             && code[i + 3] == (uint8) (v >> 16) && code[i + 4] == (uint8) (v >> 24))
            found.push_back ((int) i + 1);

    return found;
}

static void writeInt32 (std::vector<uint8>& code, int offset, uint32 v)
{
    for (int i = 0; i < 4; ++i)
        code[(size_t) offset + (size_t) i] = (uint8) (v >> (8 * i));
}

// Program::calculateChecksum, stored little-endian in the first two bytes
static void updateChecksum (std::vector<uint8>& code)
{
    uint16 n = (uint16) code.size();

    for (size_t i = 2; i < code.size(); ++i)
        n = (uint16) (n + n * 2 + code[i]);

    code[0] = (uint8) n;
    code[1] = (uint8) (n >> 8);
}

int main (int argc, char** argv)
{
    if (argc < 5) { std::fprintf (stderr, "usage: lfgen program.littlefoot out.js out.bin VARIABLE_NAME\n"); return 2; }

    auto srcFile = juce::File (juce::String (argv[1]));
    Compiler c;
    c.addNativeFunctions (lfNatives);
    auto r = c.compile (srcFile.loadFileAsString(), 512);
    if (r.failed()) { std::printf ("COMPILE FAILED: %s\n", r.getErrorMessage().toRawUTF8()); return 1; }

    auto prog = c.getCompiledProgram();
    std::vector<uint8> code (c.compiledObjectCode.begin(), c.compiledObjectCode.end());
    const int n = (int) code.size();

    std::printf ("program %d B (header says %d), heap %d B, total %d / 7200 B, globals %d, checksum %s\n",
                 n, (int) prog.getProgramSize(), (int) prog.getHeapSizeBytes(), n + (int) prog.getHeapSizeBytes(),
                 (int) prog.getNumGlobals(), prog.checksumMatches() ? "ok" : "BAD");

    if ((int) prog.getProgramSize() != n || ! prog.checksumMatches())
        return 1;

    std::vector<int> slots;

    for (uint32 k = 0; k < 0xFFu; ++k)
    {
        const auto found = findOperands (code, placeholderBase + k);

        if (found.empty())
            break;

        if (found.size() != 1)
        {
            std::printf ("placeholder %08X found %d times\n", placeholderBase + k, (int) found.size());
            return 1;
        }

        slots.push_back (found[0]);
    }

    for (uint32 k = (uint32) slots.size() + 1; k < 0xFFu; ++k)
    {
        if (! findOperands (code, placeholderBase + k).empty())
        {
            std::printf ("placeholder %08X is used but %08X isn't\n", placeholderBase + k, placeholderBase + (uint32) slots.size());
            return 1;
        }
    }

    const auto idSlots = findOperands (code, buildIdPlaceholder);

    if (slots.empty() || idSlots.size() != 1)
    {
        std::printf ("found %d value placeholders and the build id placeholder %d times\n", (int) slots.size(), (int) idSlots.size());
        return 1;
    }

    // FNV-1a over the program with its checksum and every placeholder operand zeroed
    auto masked = code;
    masked[0] = masked[1] = 0;

    for (auto s : slots)
        writeInt32 (masked, s, 0);

    writeInt32 (masked, idSlots[0], 0);

    uint32 buildId = 2166136261u;

    for (auto b : masked)
    {
        buildId ^= b;
        buildId *= 16777619u;
    }

    if ((buildId & 0xFFFFFF00u) == placeholderBase)
        buildId ^= 0x01000000u;

    writeInt32 (code, idSlots[0], buildId);
    updateChecksum (code);

    if (! Program (code.data(), (uint32) code.size()).checksumMatches())
    {
        std::printf ("checksum doesn't match after writing the build id\n");
        return 1;
    }

    juce::String js;
    js << "// Generated by lfgen from " << srcFile.getFileName() << " with the BLOCKS SDK compiler; do not edit.\n"
       << "// valueSlots[n]: byte offset of the little-endian 32-bit operand the editor overwrites with value n.\n"
       << "var " << argv[4] << " = {\n  bytes: new Uint8Array ([";

    for (int i = 0; i < n; ++i)
        js << (i % 24 == 0 ? "\n    " : "") << (int) code[(size_t) i] << (i + 1 < n ? "," : "");

    js << "\n  ]),\n  heapSize: " << (int) prog.getHeapSizeBytes()
       << ",\n  buildId: 0x" << juce::String::toHexString ((int) buildId).paddedLeft ('0', 8).toUpperCase()
       << ",\n  valueSlots: [";

    for (size_t i = 0; i < slots.size(); ++i)
        js << (i % 12 == 0 ? "\n    " : " ") << slots[i] << (i + 1 < slots.size() ? "," : "");

    js << "\n  ]\n};\n\nif (typeof module !== 'undefined') module.exports = " << argv[4] << ";\n";

    if (! juce::File (juce::String (argv[2])).replaceWithText (js, false, false, "\n"))
        return 1;

    if (! juce::File (juce::String (argv[3])).replaceWithData (code.data(), code.size()))
        return 1;

    std::printf ("wrote %s and %s: %d value placeholders, build id %08X\n", argv[2], argv[3], (int) slots.size(), buildId);
    return 0;
}
